language: cpp
sudo: required
dist: focal
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
      - cmake
      - ninja-build

before_install:
  - echo $LANG
  - echo $LC_ALL
  - ./scripts/dependencies.sh
script:
  - bash ./build.sh
after_success:
  - cd build
  - ctest
env:
  global:
    - LANG="en_US.UTF-8"
