language: cpp
sudo: required
dist: bionic
compiler:
  - gcc
os:
  - linux
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies.sh; fi
script:
  - if [ $TRAVIS_OS_NAME == linux ]; then ./build.sh fi
after_success:
  - if [ $TRAVIS_OS_NAME == linux ]; then ./build/bin/unit_tests; fi
env:
  global:
    - LANG="en_US.UTF-8"
